apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancy-deployment
  labels:
    app: fancy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fancy-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fancy-app
    spec:
      containers:
        - name: fancy-container
          image: nginx:1.21.6
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"